### ISSUE TITLE
Hide Edit and Delete buttons if the user is not able to edit or delete them

### ISSUE THREAD

**Issue by JoeKarlsson** [andimiya/gallery#12]
![gallery 1](https://cloud.githubusercontent.com/assets/4650739/23335043/5d654366-fb50-11e6-986c-c6981bded3f9.png)

**Comment by andimiya** [comment]
Hid the Edit and Delete buttons if user is not logged in.
Also hid the Add Photo button in the top menu if user is not logged in.
