### ISSUE TITLE
You are saving plain text passwords in db

### ISSUE THREAD

**Issue by JoeKarlsson** [andimiya/gallery#14]
You are not encrypting your seeder User passwords

![screenshot from 2017-02-25 11-53-08](https://cloud.githubusercontent.com/assets/4650739/23335079/0f186638-fb51-11e6-865c-b17db56065fc.png)

**Comment by JoeKarlsson** [comment]
v bad :'(

**Comment by andimiya** [comment]
Seeded user's password is now encrypted!

![image](https://cloud.githubusercontent.com/assets/20802421/23335962/2c4971ac-fb65-11e6-876e-0028cdfa8cd0.png)
