### ISSUE TITLE
STRETCH: modularize scss

### ISSUE THREAD

**Issue by nakaz** [andimiya/gallery#2]
You haven't gotten too deep into having a lot of styles so your current state of `app.scss` holding everything is totally fine. 

Later you'll want to split up your scss into its respective files like for headers, footers, images, grid view, and etc.

**Comment by andimiya** [comment]
@senakamura 
Split app.scss up into different files:
- app.scss - global styles (container, body, font)
- header.scss - styles used for the header and horizontal menu
- detail-view.scss - styles specific to the detail view page
- forms.scss - styles used across all forms
