### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by theRemix** [andimiya/gallery#4]
what happens when the promise fails?

https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L11
https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L28
https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L41
https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L54
https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L69
https://github.com/andimiya/gallery/blob/master/routes/gallery.js#L80

**Comment by andimiya** [comment]
@theRemix 

Added catches! Hopefully did it correctly..

```
.catch( err => {
      res.render('pages/error');
    });

```
